services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/rescuebite
      REDIS_URL: redis://redis:6379
      JWT_ACCESS_SECRET: rescuebite_access_secret_super_secure_32chars
      JWT_REFRESH_SECRET: rescuebite_refresh_secret_super_secure_32chars
      JWT_ACCESS_EXPIRES_IN: 15m
      JWT_REFRESH_EXPIRES_IN: 7d
      BCRYPT_ROUNDS: "12"
      PORT: "3000"
      NODE_ENV: production
      EMAIL_USER: rustemisakaev@gmail.com
      EMAIL_PASS: odxijfsfbqucxpaj
      CORS_ORIGIN: http://localhost:3001
      RATE_LIMIT_WINDOW_MS: "60000"
      RATE_LIMIT_MAX_REQUESTS: "5"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rescuebite
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
